### ISSUE TITLE
Backwards comparability 

### ISSUE THREAD

**Issue by bluzi** [lirantal/licensewatch#1]
Hi there,
It seems like your module uses features (such as default parameters), that only supported by newer version of node.
Therefore, it cannot be executed using `Node v5.12.0` 

I suggest using a transpiler to avoid tying this module to specific versions of Node.

**Comment by lirantal** [comment]
Yep, that's true.
Would you like to submit a PR that does the transpiling for licensewatch? I'd be happy to accept and merge.

**Comment by bluzi** [comment]
Sure
