### ISSUE TITLE
wrap into a simple CLI

### ISSUE THREAD

**Issue by naugtur** [lirantal/licensewatch#20]
Looks like taking the example from README and adding a few lines would make a good cli tool for listing licenses of dependencies.
Worth considering?

**Comment by lirantal** [comment]
Hi Zbyszek,
Something like this https://github.com/lirantal/licenseye ?

**Comment by naugtur** [comment]
yup - definitely that. Thanks for pointing to it :)

**Comment by lirantal** [comment]
Sorry :(

Can I propose to add you to this and the licenseye project if you're interested in pushing improvements and helping maintain them?

**Comment by naugtur** [comment]
Nothing to be sorry about. You must have misunderstood. I'm happy with the result, I'll try it out and see if I need anything more

**Comment by lirantal** [comment]
Cool 😁 Thank you for jumping in and proposing that!
